version: '2'
services:
  db:
    container_name: demodb
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root

  web:
    build:
      context: web/
    command: node /app/src/index.js
    environment:
    - DB_HOST=demodb
    ports:
    - "13000:3000"
    links:
    - db

